Add cloud-credentials config
redhat-cop/agnosticd pull request #2470
Opened 2020-09-08 02:01 UTC by stencell

##### SUMMARY

This config is very simple. It will use a set of master credentials for a sandbox or other type of account and create a set of credentials specific for a user that will be removed upon retirement. It does not create any cloud infra - networks, instances, storage, etc. - since all that is required is the credentials.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
cloud-credentials

2020-09-08 07:44 UTC, fridim commented on ansible/configs/cloud-credentials/README.adoc
> +----
Let's add the equivalent for Babylon:

```yaml
__meta__:
  aws_sandboxed: true
```


Also, make sure we set the variable to force aws-nuke.

```yaml
agnosticv_meta:
  sandboxed: true
  nuke_sandbox: true
```

In babylon, all sandboxes are marked for cleanup (with aws-nuke)  see https://github.com/redhat-gpte-devopsautomation/babylon_aws_sandbox/blob/master/tasks/release.yaml#L47.

2020-09-08 07:44 UTC, fridim commented on ansible/configs/cloud-credentials/post_software.yml
> +          student_secret_access_key: "{{ cloudformation_out_final.stack_outputs.StudentUserSecretAccessKey }}"
I would find it more logical to have this portion of code in the `post_infra.yml` playbook

2020-09-08 15:53 UTC, stencell commented
@fridim Changes made as suggested.

2020-09-08 17:44 UTC, jkupferer requested changes

2020-09-08 17:44 UTC, jkupferer commented on ansible/configs/cloud-credentials/post_infra.yml
> +            - "aws_sandbox_zone: {{ subdomain_base_suffix }}"
Setting `msg` and `data` should be separate tasks. Setting `data` should not have a loop.

2020-09-09 06:59 UTC, fridim commented
@stencell CI failed with:

```
FAIL ........ Galaxy roles cloud-credentials/sample_vars_ec2.yml
ERROR! conflicting action statements: debug, msg
The error appears to be in '/home/travis/build/redhat-cop/agnosticd/ansible/configs/cloud-credentials/pre_infra.yml': line 10, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  tasks:
    - debug:
      ^ here
ERROR: InvocationError for command /home/travis/build/redhat-cop/agnosticd/tests/static/syntax-check.sh (exited with code 2)
```

Indentation is wrong

2020-09-09 11:27 UTC, stencell commented
@fridim @jkupferer The issues you both called out have been corrected. If you can verify, release, and merge I would appreciate it!

2020-09-09 20:01 UTC, jkupferer approved these changes

2020-09-09 20:02 UTC, merged