new -user workload to create users in the iot-managed cluster
redhat-cop/agnosticd pull request #2626
Opened 2020-09-30 17:28 UTC by hguerrero

##### SUMMARY

- Changed the Camel K install to the end so there is no blocking
- Created `-user` role for creating students in a pre-provisioned cluster

##### ISSUE TYPE

- Bugfix Pull Request
- New role Pull Request

##### COMPONENT NAME

Deploy & Scale Intelligent IoT Solutions on a Managed Cloud

##### ADDITIONAL INFORMATION

```paste below

```

2020-09-30 17:43 UTC, jkupferer requested changes

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +    openshift.io/image.dockerRepositoryCheck: "2020-09-09T13:21:54Z"
This annotation should not be in version control.

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +      lastTriggeredImage: quay.io/evanshortiss/rhtr-2020-iot-datagen@sha256:8c41139447adffbf4a06e278e2d88857eab798eebfcfd0853a90e435841bd365
This line should not be in version control.

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +    openshift.io/generated-by: OpenShiftWebConsole
Is this annotation appropriate now since this is created by agnosticd?

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +    deployment.kubernetes.io/revision: "3"
This annotation should not be in version control.

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +      lastTriggeredImageID: quay.io/evanshortiss/s2i-nodejs-nginx@sha256:3046843d4fed6a84dcbb3f5a8d8009afa4d1102392257dc1dfe53ea51a171281
`lastTriggeredImageID` should not be in version control.

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +    type: Generic
Should these triggers and secrets be in version control?

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +    deployment.kubernetes.io/revision: "4"
Revision annotation should not be in version control.

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +  generation: 1
`generation` should not be in version control.

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +      lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:2bfd71b41a1591a1ea19513cb92e5c1f43d235bbdf15b114b8fddd5521e99482
`lastTriggeredImageID` should not be in version control.

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +    type: Generic
Triggers with secret values?

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +  creationTimestamp: "2020-09-11T12:02:35Z"
`creationTimestamp` should not be in version control. Also the `openshift.io/host.generated` annotation will be added automatically and probably should not be here.

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +  generation: 2
`generation`, `creationTimestamp` and `openshift.io/image.dockerRepositoryCheck` annotation should not be in version control.

2020-09-30 17:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-iot-managed-user/templates/user_project.yaml.j2
> +  creationTimestamp: "2020-09-11T12:02:35Z"
`creationTimestamp` should not be in version control

2020-10-02 08:47 UTC, satyaj commented
Hi @jkupferer we have addressed the issues raised. Can you please merge this so we can test the shared & cluster workloads.

2020-10-02 11:09 UTC, evanshortiss commented
More YAML updates in https://github.com/hguerrero/agnosticd/pull/16

I believe this should address most comments once merged.

2020-10-02 14:14 UTC, jkupferer approved these changes

2020-10-02 14:15 UTC, jkupferer commented
Merging. There are a number of code quality issues that still need to be addressed, but we can get them in later passes as we implement `yamllint` and `ansible-review` checks.

2020-10-02 14:16 UTC, merged