yamllint formatting cleanup for role bastion-lite
redhat-cop/agnosticd pull request #2633
Opened 2020-09-30 19:41 UTC by ritesh97-rh

##### SUMMARY
For the specified roles:
- Created a yamllint file to enforce formatting rules
- Made changes to existing code base to adhere to formatting requirements
- yamllint errors will be displayed during formatting checks in future development

##### ISSUE TYPE
- Code Cleanup Request

##### COMPONENT NAME
bastion-lite

2020-10-01 15:48 UTC, fridim requested changes

2020-10-01 15:48 UTC, fridim commented on ansible/roles/bastion-lite/tasks/main.yml
> +    env_type }}-{{ guid }}
This should use the other syntax, inlining is not recommended in our Contributing guidelines

Something like:

```yaml
- name: Generate host .ssh/config Template
  become: false
  template:
    src: "{{ role_path }}/templates/bastion_ssh_config.j2"
    dest: "{{ output_dir }}/ssh-config-{{ env_type }}-{{ guid }}"
  delegate_to: localhost
```

(to be tested)

2020-11-13 23:02 UTC, jkupferer approved these changes

2020-11-16 16:56 UTC, jkupferer approved these changes

2020-11-16 16:57 UTC, merged