yamllint formatting cleanup for role ocp4-workload-debezium-demo
redhat-cop/agnosticd pull request #2689
Opened 2020-10-01 22:31 UTC by ritesh97-rh

##### SUMMARY
For the specified roles:
- Create a yamllint file to enforce formatting rules
- Make changes to existing code base to adhere to formatting requirements
- yamllint errors will be displayed during formatting checks in future development

##### ISSUE TYPE
- Code Cleanup Request

##### COMPONENT NAME
ocp4-workload-debezium-demo

2020-10-02 20:21 UTC, jkupferer requested changes

2020-10-02 20:21 UTC, jkupferer commented on ansible/roles/ocp4-workload-debezium-demo/tasks/remove_workload.yml
> +            state: absent
This looks like a 4 space indent here?

2020-10-02 23:22 UTC, ritesh97-rh commented on ansible/roles/ocp4-workload-debezium-demo/tasks/remove_workload.yml
> +            state: absent
No, its 6 space, as per yamllint

2020-10-12 15:16 UTC, jkupferer commented
Merge conflict with other PR. Closing.

2020-10-12 15:16 UTC, closed without merging