yamllint formatting cleanup for role ocp4-workshop-pipelines
redhat-cop/agnosticd pull request #2741
Opened 2020-10-03 00:18 UTC by ritesh97-rh

##### SUMMARY
For the specified roles:
- Create a yamllint file to enforce formatting rules
- Make changes to existing code base to adhere to formatting requirements
- yamllint errors will be displayed during formatting checks in future development

##### ISSUE TYPE
- Code Cleanup Request

##### COMPONENT NAME
ocp4-workload-pipelines

2020-10-08 01:14 UTC, stencell commented on ansible/roles/ocp4-workload-pipelines/tasks/workload.yml
> +    src: >-
These need to be made more readable. How about something like this:

```
src: >-
  {{ 'https://github.com/tektoncd/cli/releases/download/v{0}/tkn_{0}_Linux_x86_64.tar.gz'.format(
  ocp4_workload_pipelines.tkn_version
  ) }}
```

2020-10-08 01:17 UTC, stencell commented on ansible/roles/ocp4-workload-pipelines/tasks/workload.yml
> +      ocp4_workload_pipelines_install_plan_name: >
For consistency, add a `-` for chomping to strip the final line break.

2020-10-08 01:17 UTC, stencell requested changes
few changes noted in comments

2020-11-12 15:53 UTC, jkupferer requested changes

2020-11-12 15:53 UTC, jkupferer commented on ansible/roles/ocp4-workload-pipelines/tasks/workload.yml
> +    == r_pipeline_controller_deployment.resources[0].spec.replicas | int
This would be more readable if a task var were used for `r_pipeline_controller_deployment.resources[0]`

2020-11-12 15:53 UTC, closed without merging