yamllint formatting cleanup for ocp-workload-dm7-realtime-event-decisioning
redhat-cop/agnosticd pull request #2806
Opened 2020-10-06 22:54 UTC by ritesh97-rh

##### SUMMARY
For the specified roles:
- Create a yamllint file to enforce formatting rules
- Make changes to existing code base to adhere to formatting requirements
- yamllint errors will be displayed during formatting checks in future development

##### ISSUE TYPE
- Code Cleanup Request

##### COMPONENT NAME
ocp-workload-event-decisioning

2020-10-08 13:31 UTC, stencell commented on ansible/roles/ocp-workload-dm7-realtime-event-decisioning/tasks/wait_for_deploy.yml
> +    rc_state.stdout | from_json | json_query("items[? ((status.readyReplicas == "" || status.readyReplicas
this has character escapes removed, so must be tested.

2020-10-08 13:34 UTC, stencell requested changes
Some small code changes, must be tested.

2020-11-13 19:33 UTC, jkupferer requested changes

2020-11-13 19:33 UTC, jkupferer commented on ansible/roles/ocp-workload-dm7-realtime-event-decisioning/tasks/wait_for_deploy.yml
> +    | intersect(item) |length >= 1
This logic is hard to follow, it would be better if the json query were a separate var referenced in the filter.

2020-11-13 19:33 UTC, jkupferer commented on ansible/roles/ocp-workload-dm7-realtime-event-decisioning/tasks/wait_for_deploy.yml
> +    != ''true''))].metadata.annotations."openshift.io/deployment-config.name"")
Double quote here is almost certainly an error.

2020-11-13 19:33 UTC, closed without merging