yamllint formatting cleanup for ocp-workload-optaweb-vrp
redhat-cop/agnosticd pull request #2834
Opened 2020-10-07 15:46 UTC by ritesh97-rh

##### SUMMARY
For the specified roles:
- Create a yamllint file to enforce formatting rules
- Make changes to existing code base to adhere to formatting requirements
- yamllint errors will be displayed during formatting checks in future development

##### ISSUE TYPE
- Code Cleanup Request

##### COMPONENT NAME
ocp-workload-optaweb-vrp

2020-10-07 19:10 UTC, stencell commented on ansible/roles/ocp-workload-optaweb-vrp/tasks/wait_for_deploy.yml
> +  loop: {{pod_to_wait}}
This didn't get the whitespace around the var and probably needs to be quoted.

2020-10-07 19:11 UTC, stencell commented on ansible/roles/ocp-workload-optaweb-vrp/tasks/workload.yml
> +  shell: "oc new-app --name=optaweb-vrp-frontend -e REACT_APP_BACKEND_URL=http://{{ optaweb_vrp_backend_route }} \
this should be corrected to maintain consistency with other uses of multiline `shell` in this file

2020-10-07 19:12 UTC, stencell requested changes
A couple comments to address and this needs a test since there were code changes.

2020-11-16 15:57 UTC, jkupferer requested changes

2020-11-16 15:57 UTC, jkupferer commented on ansible/roles/ocp-workload-optaweb-vrp/defaults/main.yml
> +#https://raw.githubusercontent.com/jboss-container-images/rhpam-7-openshift-image/{{pam_version_tag}}/rhpam73-image-streams.yaml
This comment style does not make sense with the linebreak

2020-11-16 15:57 UTC, jkupferer commented on ansible/roles/ocp-workload-optaweb-vrp/tasks/wait_for_deploy.yml
> +    (kind == ''ReplicationController'')].metadata.annotations."openshift.io/deployment-config.name"")
This `''` quote is not right.

2020-11-16 15:57 UTC, closed without merging