yamllint formatting cleanup for ocp-workload-pam7-cc-dispute-dmn-pmml
redhat-cop/agnosticd pull request #2836
Opened 2020-10-07 16:00 UTC by ritesh97-rh

##### SUMMARY
For the specified roles:
- Create a yamllint file to enforce formatting rules
- Make changes to existing code base to adhere to formatting requirements
- yamllint errors will be displayed during formatting checks in future development

##### ISSUE TYPE
- Code Cleanup Request

##### COMPONENT NAME
ocp-workload-pam7-cc-dispute-dmn-pmml

2020-10-07 18:58 UTC, stencell requested changes
This one has changes to commands that remove escaped chars. It needs to be tested before merging.

2020-10-07 19:51 UTC, ritesh97-rh commented
Would talk to Jonathan about testing. I'm only on this project for a short period.

2020-11-16 15:55 UTC, jkupferer requested changes

2020-11-16 15:55 UTC, jkupferer commented on ansible/roles/ocp-workload-pam7-cc-dispute-dmn-pmml/tasks/prometheus_workload.yml
> +      -n {{ OCP_PROJECT }}
This line breaking is really hard to read.

2020-11-16 15:55 UTC, jkupferer commented on ansible/roles/ocp-workload-pam7-cc-dispute-dmn-pmml/tasks/rhpam_openshift_dmn_pmml_workload.yml
> +    "value": "rhpam-businesscentral-rhel8-dmn-pmml:latest"}]'
Line break in the middle of an argument?

2020-11-16 15:55 UTC, closed without merging