Cleanup config ocp4-cluster for yamllint
redhat-cop/agnosticd pull request #2987
Opened 2020-10-12 13:49 UTC by jkupferer

##### SUMMARY

Cleanup of ocp4-cluster for style

##### ISSUE TYPE

- Cleanup Pull Request

##### COMPONENT NAME

config ocp4-cluster

2020-10-12 15:41 UTC, stencell commented on ansible/configs/ocp4-cluster/pre_software.yml
> +    when: et_env_authorized_key | bool
typo, missing the s in `set`

2020-10-12 15:44 UTC, stencell requested changes
One comment to address @jkupferer

2020-11-16 15:19 UTC, jkupferer commented
@stencell rebased off latest and fixed up some things. Can i get another review?

2020-11-16 18:59 UTC, stencell approved these changes

2020-11-16 18:59 UTC, merged