Update main.yml
redhat-cop/agnosticd pull request #3224
Opened 2020-11-23 15:11 UTC by rut31337

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New config Pull Request
- New role Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2020-11-23 15:18 UTC, wkulhanek commented
Why? Will this break existing configs?

2020-11-23 15:23 UTC, jkupferer commented
@rut31337 Please be sure to title your PR to indicate the role or config changed/added/removed

2020-11-24 19:12 UTC, thomas-crowe requested changes
I think this will cause problems, since hostnames are not unique unless they include the GUID e.g. {{ host }}-{{ guid }}.{{osp_cluster_dns_zone}}"

2020-11-24 19:26 UTC, thomas-crowe approved these changes

2020-11-24 19:26 UTC, merged