machinesSubnet parameter added
redhat-cop/agnosticd pull request #3249
Opened 2020-12-02 15:29 UTC by miteshget

##### SUMMARY
For flat network machinesSubnet: {{ ocp_network_subnet_id }} parameter added with condition in install-config.yaml.j2 template

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
role: host-ocp4-installer

2020-12-02 15:41 UTC, wkulhanek approved these changes

2020-12-02 15:42 UTC, wkulhanek commented
I would suggest adding a comment to the default_vars_osp.yml file as well. Leave it commented out but have documentation there...

2020-12-02 16:00 UTC, jkupferer reviewed
How will we use this? How would someone know how to set the `ocp_network_subnet_id`?

2020-12-02 16:47 UTC, miteshget commented
@jkupferer @wkulhanek `ocp_network_subnet_id` needs UUID of subnet. So in our case we have added a task in post_infra.yml which will fetch subnet id and store that value in the variable. E.g

```    - name: find ocp network subnet id
      command: openstack subnet list -f json
      register: __subnet_ids
    - name: set ocp network subnetid
      set_fact:
        ocp_network_subnet_id: "{{ item.Network }}" 
      when: 'item.Name == guid + "-ocp-subnet"'
      loop: "{{ __subnet_ids.stdout }}"```

2020-12-02 16:50 UTC, wkulhanek commented
@miteshget That's not a good solution. Because if you only have this in post-infra of that one configs this will break in other configs. I'd suggest moving this to the install role with a block conditional.

2020-12-02 17:28 UTC, jkupferer requested changes
We need to figure out how to set `machinesSubnet` based on the uuid created in the heat template. The parameter used to configure this should be named something that is easy to understand, something like `ocp_use_single_network` or something of that sort.

2020-12-15 10:26 UTC, miteshget commented
Hi @wkulhanek and @jkupferer,

I have added task in tasks/osp_pre.yml to find subnet id which will run when `ocp_use_single_network` variable as boolean set.

Hope this time it fulfills all the requirements.

Please review and merge or comment for improvements.

2020-12-15 10:32 UTC, miteshget commented
JFI- I have run successful test just by using following variables -

![osp_new_infra](https://user-images.githubusercontent.com/44154255/102203660-de70b900-3eee-11eb-8710-b1e5416bc3df.png)
`ocp_use_single_network: true`
`ocp4_installer_version: 4.6.1`

attach is network topology after deployment

2020-12-16 03:57 UTC, prakhar1985 commented
@miteshget looks good. I think moving it to the role and not adding anything in post_software is a good recommendation.

2020-12-16 03:57 UTC, prakhar1985 approved these changes

2021-01-05 14:11 UTC, miteshget commented
Hello @wkulhanek and @jkupferer, could you please spare some time to review this PR again?

2021-01-05 14:38 UTC, wkulhanek requested changes
@miteshget This looks good - but I'd like another when condition to only run the osp network stuff when the variable ocp_use_single_network is set to true.

2021-01-05 14:38 UTC, wkulhanek commented on ansible/roles/host-ocp4-installer/tasks/main.yml
> +  when: cloud_provider == "osp"
I think we may want another when here to only do this when ocp_use_single_network is true

2021-01-06 06:34 UTC, miteshget commented
@wkulhanek I have added condition, please review.

2021-01-06 14:32 UTC, wkulhanek approved these changes

2021-01-06 14:32 UTC, merged