Update ocp4-workload-quarkus-workshop to rebase user info
redhat-cop/agnosticd pull request #3879
Opened 2021-06-18 13:24 UTC by danieloh30

##### SUMMARY
Update ocp4-workload-quarkus-workshop to rebase user info

##### ISSUE TYPE

- Feature Pull Request
- 
##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2021-06-18 13:43 UTC, jkupferer requested changes

2021-06-18 13:43 UTC, jkupferer commented on ansible/roles/ocp4-workload-quarkus-workshop/tasks/post_workload.yml
> +        Workshop User Guide: http://web-{{modules}}-guides.{{ route_subdomain }}
It looks like `modules` is a list?
```
- name: create module list
  set_fact:
    modules: "{{ module_type.split(';') | map('trim') | list }}"
```

Based on that I think we may need something like:
```
- name: lab data for user info
  agnosticd_user_info:
    user: "{{ item }}"
      data:
        msg: |
          Username: {{ item }}
          {% for m in modules %}
          Workshop User Guide: http://web-{{ m }}-guides.{{ route_subdomain }}
          {% endfor %}
```

2021-06-18 20:47 UTC, rhjcd approved these changes

2021-06-19 02:04 UTC, jkupferer approved these changes

2021-06-19 02:04 UTC, merged