Updated ocp4-workload-dil-agile-integration to fix SSO service Account roles
redhat-cop/agnosticd pull request #3935
Opened 2021-07-07 08:47 UTC by satyaj

##### SUMMARY

The SSO operator does not have resources to update the Service Account roles for a client. This causes a manual configuration requirement during the labs, and these are overwritten on restart by the operator. Fixed this by using the Admin API to create the realm and the clients with service account roles configured.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ocp4-workload-dil-agile-integration

##### ADDITIONAL INFORMATION

```paste below

```

2021-07-07 09:11 UTC, d-jana approved these changes
LGTM

2021-07-07 10:02 UTC, fridim requested changes

2021-07-07 10:02 UTC, fridim commented on ansible/roles/ocp4-workload-dil-agile-integration/tasks/provision_sso.yaml
> +- set_fact: TKN={{ (token_text.stdout | from_json).access_token }}
use the yaml notation and not inline, see contributing guidelines

2021-07-07 10:02 UTC, fridim commented on ansible/roles/ocp4-workload-dil-agile-integration/tasks/provision_sso.yaml
> +- debug: var=TKN
remove debug or add `verbosity: 2` or more

2021-07-07 10:02 UTC, fridim commented on ansible/roles/ocp4-workload-dil-agile-integration/tasks/user_sso_realm.yaml
> +- set_fact: current_user='user{{__user_number}}'
do not use inline notation

2021-07-07 10:02 UTC, fridim commented on ansible/roles/ocp4-workload-dil-agile-integration/tasks/user_sso_realm.yaml
> +    body:  "{{ lookup('file', 'sso-user-realm.json') | replace('%user%', current_user) | from_json }}"
Why use `replace` instead of just passing a variable and use  `template` instead of `file` ?

2021-07-07 10:02 UTC, fridim commented on ansible/roles/ocp4-workload-dil-agile-integration/files/threescale-realm.json
> +  }
need newline at the end of the file

2021-07-07 11:25 UTC, satyaj commented
Made the changes requested. @fridim please review and merge. Thanks

2021-07-12 12:01 UTC, fridim approved these changes

2021-07-12 12:01 UTC, merged