workload for "hands on openshift 4.8" new class
redhat-cop/agnosticd pull request #4021
Opened 2021-08-05 01:40 UTC by newgoliath

##### SUMMARY

1. adds hands_on_openshift_48 workload 
  creates a few projects and deploys some sample apps
1. Fixes ocp4_workload_logging version_compare issues
  No longer supports OpenShift <4.6

##### ISSUE TYPE
- New role Pull Request
- Role bug fix pull request

##### COMPONENT NAME
* ocp4_workload_hands_on_openshift_48
* ocp4_workload_logging

2021-08-05 02:32 UTC, stencell approved these changes
We're gonna need a bigger boat.

2021-08-05 02:39 UTC, varodrig approved these changes

2021-08-06 00:46 UTC, jkupferer requested changes

2021-08-06 00:46 UTC, jkupferer commented on ansible/roles_ocp_workloads/ocp4_workload_hands_on_openshift_48/files/json_logs_pod.yaml
> +code: &code-str |
Let's please avoid yaml anchors. This is weird and scary :fearful:

2021-08-06 00:46 UTC, jkupferer commented on ansible/roles_ocp_workloads/ocp4_workload_hands_on_openshift_48/files/json_logs_pod.yaml
> +        - *code-str
Can just put the code block quote here :smile:

2021-08-10 19:45 UTC, jkupferer commented on ansible/roles_ocp_workloads/ocp4_workload_hands_on_openshift_48/tasks/workload.yml
> +#  - argocd_app_of_apps.yaml
What's the story with this?

2021-08-10 19:49 UTC, merged