[WIP] New vmc cloud provider
redhat-cop/agnosticd pull request #5137
Opened 2022-07-25 14:42 UTC by agonzalezrh

2022-12-12 14:28 UTC, ahsen-shah approved these changes

2022-12-14 09:04 UTC, fridim commented on ansible/cloud_providers/vmc_destroy_env.yml
> +        --force-with-deps
mhh  we should probably have this setup differently.
Requirement files should be used with pinned version.

requirements-vmc.yml?

2022-12-14 10:07 UTC, fridim requested changes
Why do you remove ansible/configs/sandbox/infra.yml?

Do you delete all the dns record  you created?

2022-12-14 10:46 UTC, agonzalezrh commented on ansible/cloud_providers/vmc_infrastructure_deployment.yml
> +        creates: "{{ playbook_dir }}/../collections/ansible_collections/community/vmware"
could you check the new approach?

2022-12-14 14:34 UTC, agonzalezrh commented on ansible/roles-infra/infra-dns/defaults/main.yml
> +  hostvars
It is more complex, the public IPs are on NSX-T and not on VMware, so I get the public ips first

https://github.com/redhat-cop/agnosticd/blob/vsphere/ansible/roles-infra/infra-dns/tasks/nested_loop.yml#L10

2022-12-20 19:25 UTC, closed without merging