[ee-multicloud-public] Fix openstacksdk python library
redhat-cop/agnosticd pull request #6963
Opened 2023-08-31 13:34 UTC by agonzalezrh

Newer version doesn't allow to filter by metadata keys which doesn't exist (i.e. *guid*)

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New config Pull Request
- New role Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-08-31 23:39 UTC, bbethell-1 approved these changes

2023-09-05 08:28 UTC, bbethell-1 approved these changes

2023-09-05 12:24 UTC, fridim requested changes
Can you link the upstream bug as a comment in the file?
So we know when to switch it back

2023-09-05 12:32 UTC, fridim commented
according to diff, latest stable is already openstacksdk 1.3.1

2023-09-06 08:04 UTC, bbethell-1 approved these changes

2023-09-06 08:11 UTC, fridim approved these changes

2023-09-06 08:12 UTC, merged