Adding cloud provider OpenShift CNV (OpenShift Virtualization)
redhat-cop/agnosticd pull request #7085
Opened 2023-09-27 16:45 UTC by agonzalezrh

Please double check everything

2023-09-27 16:56 UTC, rut31337 commented on ansible/cloud_providers/openshift_cnv_destroy_env.yml
shouldnt this be in the execution environment?

2023-09-28 07:29 UTC, wkulhanek commented on ansible/cloud_providers/openshift_cnv_destroy_env.yml
> +      command: >-
This should be in the EE (it is in :latest for me).

2023-09-28 07:29 UTC, wkulhanek commented on ansible/cloud_providers/openshift_cnv_infrastructure_deployment.yml
> +      command: >-
Same here?

2023-09-28 07:29 UTC, wkulhanek commented on ansible/cloud_providers/openshift_cnv_infrastructure_deployment.yml
> +      include_role:
ansible.builtin.include_role

2023-09-28 08:11 UTC, fridim requested changes
Thanks for the PR.

I'm wondering if there is a way to specify retries/wait at the k8s module level for all those call to the openshift API, or if we have to deal with it at the ansible level with the classical `register + retries + until`

Update the documentation in `docs/` to add the new cloud-provider?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/defaults/main.yaml
> +openshift_cnv_project_name: "{{ env_type }}-{{ guid }}"
`uuid`?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/check_network.yaml
> +  kubernetes.core.k8s_info:
retries?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_instance.yaml
> +    _instance_interfaces: "{{ _instance_interfaces + [{'name': _network, 'macAddress': _instance.fixed_macs[_network]|default('2c:c2:60'|random_mac),'bridge': {}, 'model': 'e1000e', 'pciAddress': '00
formatting difficult to read

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_instance.yaml
> +    _instance_networks: "{{ _instance_networks + [{'name': _network, 'multus': {'networkName': _network + guid}} if _network != 'default' else {'name': 'default', 'pod': {}}] }}"
formatting

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_instance.yaml
> +    _instance_volumes: "{{ _instance_volumes|from_yaml + [{'name': _disk.metadata.name, 'dataVolume': {'name': _disk.metadata.name} }] }}"
formatting

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_instance.yaml
> +     'networkData': _instance.networkdata|default('')}}] }}"
formatting

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_network.yaml
> +  kubernetes.core.k8s:
retries?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_network.yaml
> +    config: "{'cniVersion':'0.3.1','type':'ovn-k8s-cni-overlay','topology':'layer2','name': '{{ _network.name }}{{ guid }}', 'netAttachDefName': '{{ openshift_cnv_project_name }}/{{ _network.name }}{
formatting

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_project.yaml
> +  kubernetes.core.k8s:
retries?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_project.yaml
> +  kubernetes.core.k8s:
retries?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_routes.yaml
> +  kubernetes.core.k8s:
retries?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_routes.yaml
> +  kubernetes.core.k8s:
retries?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_service.yaml
> +  kubernetes.core.k8s:
retries?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/create_services.yaml
> +  kubernetes.core.k8s:
retries?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/delete_networks.yaml
> +  kubernetes.core.k8s_info:
retries?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/start_instances.yaml
> +  kubernetes.core.k8s_info:
retries?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/status_instances.yaml
> +  kubernetes.core.k8s_info:
retries?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/status_instances.yaml
> +  agnosticd_user_info:
what about `agnosticd_user_data`?

2023-09-28 08:11 UTC, fridim commented on ansible/roles-infra/infra-openshift-cnv-resources/tasks/stop_instances.yaml
> +  kubernetes.core.k8s_info:
retries?

2023-10-04 16:26 UTC, fridim approved these changes

2023-10-05 12:40 UTC, merged