New Catalog item: Test Containers Demo
redhat-cop/agnosticd pull request #8041
Opened 2024-05-15 20:53 UTC by deewhyweb

##### SUMMARY

##### ISSUE TYPE

- New role Pull Request

##### COMPONENT NAME
Test containers Demo

##### ADDITIONAL INFORMATION

```New demo catalog item to install and configure Docker Test Containers on OpenShift
```

2024-05-15 21:01 UTC, bbethell-1 approved these changes

2024-05-15 21:02 UTC, danieloh30 commented on ansible/roles/ocp4-workload-test-containers/meta/main.yml
> +    This catalog entry is developed and maintained by the Application Services BU.
shouldn't it be AppDeveloper BU?

2024-05-16 10:36 UTC, juliaaano requested changes
Please consider the following changes:

1. Assuming this workload runs on OpenShift, please move it to the `roles_oct_workloads` folder.
2. Use underscore instead of dashes for the role name. I suggest this name: `ocp4_workload_testcontainers`.
3. We've got workloads to install kubevirt and pipelines. Could you use them on your agnosticV config instead of installing on your own (ocp4_workload_kubevirt, ocp4_workload_pipelines)?
4. User your own variables in defaults/main.yaml, with the prefix of the role name. For example, ocp4_workload_testcontainers_num_users.
5. The other defaults/main.yml prefixed with workshop are not used, I noticed. Please remove them.
6. Finally, please consider extracting some vars, such as tcc-operator CSV, using the naming convention described above.

2024-05-16 13:04 UTC, deewhyweb commented on ansible/roles/ocp4-workload-test-containers/meta/main.yml
> +    This catalog entry is developed and maintained by the Application Services BU.
Thanks Dan!

2024-05-16 16:26 UTC, deewhyweb commented
@juliaaano I've made those changes, please review again.

Thanks,
Philip

2024-05-20 14:03 UTC, juliaaano approved these changes

2024-05-20 14:42 UTC, merged