Preserve user-data by default across run
redhat-cop/agnosticd pull request #8752
Opened 2024-11-04 16:29 UTC by fridim

That allows to use user-data from provision, in destroy or stop/start when:

- developping locally
- agnosticd_restore/save_output_dir  is used in production

2024-11-04 16:35 UTC, jkupferer requested changes
discussion in slack...

2024-11-04 16:57 UTC, bbethell-1 approved these changes

2024-11-04 17:45 UTC, jkupferer commented on ansible/update.yml
> +    - name: Set ACTION to provision
Task name...

2024-11-04 17:47 UTC, jkupferer commented on ansible/destroy.yml
> +    - name: Set ACTION to provision
Task name here too.

2024-11-06 19:27 UTC, tonykay approved these changes

2024-11-08 10:06 UTC, bbethell-1 approved these changes

2024-11-08 14:30 UTC, merged